services:
  app:
    build: .
    container_name: rop-management-api
    restart: always
    depends_on:
      - db
    environment:
      HOST: ${HOST}
      PORT: ${PORT}
      DB_URL: ${DB_URL}
      ISU_API_KEY: ${ISU_API_KEY}
