"""added team and checkpoint

Revision ID: 11af9d9d11d7
Revises: cf3a248ac15a
Create Date: 2025-12-14 01:27:02.592743

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11af9d9d11d7'
down_revision: Union[str, Sequence[str], None] = 'cf3a248ac15a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('team',
    sa.Column('team_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('owner_id', sa.BigInteger(), nullable=True),
    sa.Column('is_visible', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user.user_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('team_id')
    )
    op.create_table('checkpoint',
    sa.Column('checkpoint_id', sa.BigInteger(), nullable=False),
    sa.Column('stream_id', sa.BigInteger(), nullable=False),
    sa.Column('checkpoint_date', sa.Date(), nullable=True),
    sa.Column('materials', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['stream_id'], ['stream.stream_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('checkpoint_id')
    )
    op.create_table('team_course',
    sa.Column('team_id', sa.BigInteger(), nullable=False),
    sa.Column('course_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['course.course_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['team.team_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('team_id', 'course_id')
    )
    op.create_table('team_member',
    sa.Column('team_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['team.team_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('team_id', 'user_id')
    )
    op.create_table('team_tag',
    sa.Column('team_id', sa.BigInteger(), nullable=False),
    sa.Column('tag_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.tag_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['team.team_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('team_id', 'tag_id')
    )
    op.create_table('checkpoint_tag',
    sa.Column('checkpoint_id', sa.BigInteger(), nullable=False),
    sa.Column('tag_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['checkpoint_id'], ['checkpoint.checkpoint_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.tag_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('checkpoint_id', 'tag_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('checkpoint_tag')
    op.drop_table('team_tag')
    op.drop_table('team_member')
    op.drop_table('team_course')
    op.drop_table('checkpoint')
    op.drop_table('team')
    # ### end Alembic commands ###
