"""initial migration

Revision ID: cf3a248ac15a
Revises: 
Create Date: 2025-12-11 23:21:35.153371

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf3a248ac15a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


education_form = sa.Enum('offline', 'online', 'combined', name='education_form')
education_level = sa.Enum('bachelor', 'master', 'phd', name='education_level')
education_lang = sa.Enum('ru', 'en', name='education_lang')
teacher_position = sa.Enum('junior', 'middle', 'senior', name='teacher_position')
student_status = sa.Enum('send_down', 'academic_leave', 'transferred_from', 'transferred_to', name='student_status')


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course',
    sa.Column('course_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('credits', sa.Integer(), nullable=False),
    sa.Column('form', education_form, nullable=False),
    sa.Column('is_elective', sa.Boolean(), nullable=False),
    sa.Column('syllabus_link', sa.String(), nullable=True),
    sa.Column('rpd_link', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('course_id')
    )
    op.create_table('faculty',
    sa.Column('faculty_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('short_name', sa.VARCHAR(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('faculty_id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('short_name')
    )
    op.create_table('semester',
    sa.Column('semester_id', sa.BigInteger(), nullable=False),
    sa.Column('semester_number', sa.Integer(), nullable=False),
    sa.Column('study_year', sa.VARCHAR(length=9), nullable=False),
    sa.PrimaryKeyConstraint('semester_id')
    )
    op.create_table('tag',
    sa.Column('tag_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('tag_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('surname', sa.String(), nullable=False),
    sa.Column('patronymic', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('isu_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('course_tag',
    sa.Column('course_id', sa.BigInteger(), nullable=False),
    sa.Column('tag_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['course.course_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.tag_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('course_id', 'tag_id')
    )
    op.create_table('prerequisite',
    sa.Column('course_id', sa.BigInteger(), nullable=False),
    sa.Column('prerequisite_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['course.course_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['prerequisite_id'], ['course.course_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('course_id', 'prerequisite_id')
    )
    op.create_table('program',
    sa.Column('program_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('accreditation_year', sa.Integer(), nullable=False),
    sa.Column('level', education_level, nullable=False),
    sa.Column('form', education_form, nullable=False),
    sa.Column('lang', education_lang, nullable=False),
    sa.Column('duration_years', sa.Integer(), nullable=False),
    sa.Column('faculty_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['faculty_id'], ['faculty.faculty_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('program_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('stream',
    sa.Column('stream_id', sa.BigInteger(), nullable=False),
    sa.Column('semester_id', sa.BigInteger(), nullable=False),
    sa.Column('course_id', sa.BigInteger(), nullable=False),
    sa.Column('teacher_id', sa.BigInteger(), nullable=True),
    sa.Column('form', education_form, nullable=False),
    sa.Column('name', sa.VARCHAR(length=15), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('exam_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['course.course_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['semester_id'], ['semester.semester_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['teacher_id'], ['user.user_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('stream_id')
    )
    op.create_table('teacher',
    sa.Column('teacher_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('faculty_id', sa.BigInteger(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('position', teacher_position, nullable=False),
    sa.ForeignKeyConstraint(['faculty_id'], ['faculty.faculty_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('teacher_id')
    )
    op.create_table('user_tag',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('tag_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.tag_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'tag_id')
    )
    op.create_table('cohort',
    sa.Column('cohort_id', sa.BigInteger(), nullable=False),
    sa.Column('program_id', sa.BigInteger(), nullable=False),
    sa.Column('cohort_year', sa.Integer(), nullable=False),
    sa.Column('director_id', sa.BigInteger(), nullable=True),
    sa.Column('manager_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['director_id'], ['user.user_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['manager_id'], ['user.user_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['program_id'], ['program.program_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('cohort_id')
    )
    op.create_table('specialization',
    sa.Column('specialization_id', sa.BigInteger(), nullable=False),
    sa.Column('cohort_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['cohort_id'], ['cohort.cohort_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('specialization_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('group',
    sa.Column('group_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=10), nullable=False),
    sa.Column('program_id', sa.BigInteger(), nullable=False),
    sa.Column('specialization_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['program_id'], ['program.program_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['specialization_id'], ['specialization.specialization_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('group_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('planned_course',
    sa.Column('planned_course_id', sa.BigInteger(), nullable=False),
    sa.Column('cohort_id', sa.BigInteger(), nullable=False),
    sa.Column('specialization_id', sa.BigInteger(), nullable=True),
    sa.Column('course_id', sa.BigInteger(), nullable=False),
    sa.Column('semester_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['cohort_id'], ['cohort.cohort_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['course_id'], ['course.course_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['semester_id'], ['semester.semester_id'],  ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['specialization_id'], ['specialization.specialization_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('planned_course_id')
    )
    op.create_table('student',
    sa.Column('student_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('cohort_id', sa.BigInteger(), nullable=False),
    sa.Column('group_id', sa.BigInteger(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('status', student_status, nullable=True),
    sa.ForeignKeyConstraint(['cohort_id'], ['cohort.cohort_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['group_id'], ['group.group_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('student_id')
    )
    op.create_table('student_stream',
    sa.Column('student_id', sa.BigInteger(), nullable=False),
    sa.Column('stream_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['stream_id'], ['stream.stream_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['student.student_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('student_id', 'stream_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('student_stream')
    op.drop_table('student')
    op.drop_table('planned_course')
    op.drop_table('group')
    op.drop_table('specialization')
    op.drop_table('cohort')
    op.drop_table('user_tag')
    op.drop_table('teacher')
    op.drop_table('stream')
    op.drop_table('program')
    op.drop_table('prerequisite')
    op.drop_table('course_tag')
    op.drop_table('user')
    op.drop_table('tag')
    op.drop_table('semester')
    op.drop_table('faculty')
    op.drop_table('course')
    student_status.drop(op.get_bind())
    teacher_position.drop(op.get_bind())
    education_lang.drop(op.get_bind())
    education_level.drop(op.get_bind())
    education_form.drop(op.get_bind())
    # ### end Alembic commands ###
